language: scala
scala:
  - 2.12.8
before_install:
  - openssl aes-256-cbc -K $encrypted_f7a2d53f3383_key -iv $encrypted_f7a2d53f3383_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script:
  - sbt publishLocalSigned
